#!/bin/bash
#Yabai config
#layout
yabai -m config layout bsp

#Window placement
yabai -m config window_placement second_child

#padding
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

#mouse settings
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
#yabai -m window --focus mouse
yabai -m config mouse_follows_focus on

#disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Shottr$" manage=off
#yabai -m rule --add app="^ProtonVPN$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
#yabai -m rule --add app="^WhatsApp$" manage=off

#window opacity
#yabai -m config window_opacity on
#yabai -m config active_window_opacity 0.9
#yabai -m config normal_window_opacity 0.8

#borders
borders active_color=0xff74c7ec inactive_color=0xffcba6f7 width=6.0 hidpi=on &

#sketchybar
yabai -m config external_bar all:40:0

# Sketchybar integration
yabai -m signal --add event=space_changed action="sketchybar --trigger space_change"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger window_focus"

#Window shadows
yabai -m config window_shadow off

# Focus space by index
yabai -m space --focus 1

# Scriptting addons
# yabai --load-sa
