source-file ~/.config/tmux/tmux.reset.conf

set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g prefix ^A
set -g base-index 1
set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 1000000
set -g renumber-windows on
set -g set-clipboard on
set -g status-position top
set -g mouse on
setw -g mode-keys vi

set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'magenta'
set -g @floax-text-color 'blue'
set -g @floax-bind 'p'
set -g @floax-change-path 'true'

set -g @sessionx-bind-zo-new-window 'ctrl-y'
set -g @sessionx-auto-accept 'off'
set -g @sessionx-custom-paths "$HOME/dev"
set -g @sessionx-bind 'o'
set -g @sessionx-x-path "$HOME/dev"
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-custom-paths-subdirectories 'false'
set -g @sessionx-filter-current 'false'

set -g @continuum-restore 'on'

# catppuccin v2
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_status_background "#282c35"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #W "
set -g @catppuccin_window_current_text " #W "
set -g @catppuccin_window_flags "none"

# override module text before catppuccin loads (it uses -ogq so won't override these)
set -g @catppuccin_directory_text "#(echo #{pane_current_path} | sed 's|$HOME|~|')"
set -g @catppuccin_date_time_text " %H:%M"

set -g status-style "bg=#282c35"
set -g status-left " "
set -g status-left-length 100
set -g status-right-length 100

set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_date_time}"
set -ag status-right "#{E:@catppuccin_status_session}"

run '~/.config/tmux/plugins/tpm/tpm'
